[supabase]
url = "https://xhydpuugdxcrhmvtwzbd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeWRwdXVnZHhjcmhtdnR3emJkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzEzOTc4NiwiZXhwIjoyMDcyNzE1Nzg2fQ.bQG3RbV2qQy5XTANocUlw4uTohTHC92NWmdcVk7L2OU"
