[supabase]
url = "https://odgrorgerfcuyrzgnoqh.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZ3JvcmdlcmZjdXlyemdub3FoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzMxNDg0NCwiZXhwIjoyMDcyODkwODQ0fQ.1ldw2j8yb6ZxmkPHLSAWDudKKCv7qKot5_ARJVmfVcI"
